version: '3'
services:
  mysql:
    image: mysql:5.7.14
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "shalog"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
    ]
    expose:
      - "3306"
    ports:
      - "3306:3306"
  kplcloud:
    image: dudulu/shalom:v0.0.3-test
    command: /go/bin/shalom start -p :8080 -c /etc/shalom/app.cfg
    environment:
      GOPATH: "/go"
      USERNAME: "admin" # 如果是login_type: email 那这是初始化管理员的登陆密码
      PASSWORD: "admin"
      SQL_PATH: ./database/db.sql
    volumes:
      - ./app.cfg-sample:/etc/shalom/app.cfg
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile